services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "secret"
      DB_DATABASE: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DJANGO_DEBUG: 1
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "8432:5432"
